services:
  redis-service:
    container_name: redis-service
    image: redis
    networks:
      - game-network

  game-api-service:
    container_name: game-api-service
    image: goiac/joc-apps-game-api-service:latest
    build: 
      context: ./GameAPI
      dockerfile: Dockerfile
    ports:
      - "66:8080"
    environment:
      - MONGODB_CLUSTER=mongodb+srv://sa:parolagameSA@cluster0.hpfqy.mongodb.net/gamedb?retryWrites=true&w=majority
      - REDIS_HOST=redis-service
    depends_on:
      - redis-service
    networks:
      - game-network

  runner-service:
    image: goiac/joc-apps-runner-service:latest
    container_name: runner_service
    build: 
      context: ./runnerService
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis-service
    depends_on:
      - redis-service
    networks:
      - game-network
    ports:
      - "8088:8080"

networks:
  game-network:
    driver: bridge
    name: game-network