services:
  redis-service:
    container_name: redis-service
    image: redis
    networks:
      - game-network

  building-api:
      container_name: buildings-api
      image: goiac/joc-apps-buildings-api-service:latest
      build:
          context: ./BuildingsApi
          dockerfile: Dockerfile
      ports:
          - "68:8081"
      environment:
          - REDIS_HOST=redis-service
      env_file:
          - compose.env
      depends_on:
          - redis-service
      networks:
          - game-network

  game-api-service:
    container_name: game-api-service
    image: goiac/joc-apps-game-api-service:latest
    build:
      context: ./GameAPI
      dockerfile: Dockerfile
    ports:
      - "66:8080"
    environment:
      - REDIS_HOST=redis-service
    env_file:
      - compose.env
        
    depends_on:
      - redis-service
    networks:
      - game-network

  runner-service:
    image: goiac/joc-apps-runner-service:latest
    container_name: runner_service
    build:
      context: ./runnerService
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis-service
    depends_on:
      - redis-service
    networks:
      - game-network
    ports:
      - "8088:8080"

networks:
  game-network:
    driver: bridge
    name: game-network