version: '3'
services:
  redis_container:
    container_name: redis_container
    image: redis
    networks:
      - game_network

  game_api_container:
    container_name: game_api_container
    build: 
      context: ./GameAPI
      dockerfile: Dockerfile
    ports:
      - "66:8080"
    environment:
      - MONGODB_CLUSTER=mongodb+srv://sa:parolagameSA@cluster0.hpfqy.mongodb.net/gamedb?retryWrites=true&w=majority
      - REDIS_HOST=redis_container
    depends_on:
      - redis_container
    networks:
      - game_network

  runner_service:
    container_name: runner_service
    build: 
      context: ./runnerService
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis_container
    depends_on:
      - redis_container
    networks:
      - game_network

networks:
  game_network:
    driver: bridge